[package]
name = "iced_winit"
version = "0.7.0"
authors = ["Héctor Ramón Jiménez <hector0193@gmail.com>"]
edition = "2021"
description = "A winit runtime for Iced"
license = "MIT"
repository = "https://github.com/iced-rs/iced"
documentation = "https://docs.rs/iced_winit"
keywords = ["gui", "ui", "graphics", "interface", "widgets"]
categories = ["gui"]

[features]
trace = ["tracing", "tracing-core", "tracing-subscriber"]
chrome-trace = ["trace", "tracing-chrome"]
debug = ["iced_native/debug"]
system = ["sysinfo"]
application = []
a11y = ["iced_accessibility"]

[dependencies]
window_clipboard = "0.2"
log = "0.4"
thiserror = "1.0"

[dependencies.winit]
version = "0.27"
git = "https://github.com/iced-rs/winit.git"
rev = "940457522e9fb9f5dac228b0ecfafe0138b4048c"

[dependencies.iced_native]
version = "0.8"
path = "../native"

[dependencies.iced_graphics]
version = "0.6"
path = "../graphics"

[dependencies.iced_futures]
version = "0.5"
path = "../futures"

[dependencies.tracing]
version = "0.1.37"
optional = true
features = ["std"]

[dependencies.tracing-core]
version = "0.1.30"
optional = true

[dependencies.tracing-subscriber]
version = "0.3.16"
optional = true
features = ["registry"]

[dependencies.tracing-chrome]
version = "0.7.0"
optional = true

[target.'cfg(target_os = "windows")'.dependencies.winapi]
version = "0.3.6"

[target.'cfg(target_arch = "wasm32")'.dependencies.web-sys]
version = "0.3"
features = ["Document", "Window"]

[dependencies.sysinfo]
version = "0.23"
optional = true

[dependencies.iced_accessibility]
version = "0.1.0"
path = "../accessibility"
optional = true
